ALTER TABLE fco_nations ADD COLUMN is_deleted TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE fco_leagues ADD COLUMN is_deleted TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE fco_clubs ADD COLUMN is_deleted TINYINT(1) NOT NULL DEFAULT 0;
